apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app-service
  labels:
    app: ecommerce-app
spec:
  selector:
    app: ecommerce-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer