name: "Building and Pushing Docker Image"
on:
  workflow_dispatch:   # allows manual triggering from GitHub UI
  push:
    branches:
      - main
    paths:
      - ecommerce-app/**

env:
  DO_CONNECT_TOKEN: ${{ secrets.DO_CONNECT_TOKEN }} # DigitalOcean API token stored in GitHub Secrets
  DEPLOYMENT_NAME: ${{ vars.DEPLOYMENT_NAME }}
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
  DO_CLUSTER_NAME: ${{ vars.DO_CLUSTER_NAME }} # DigitalOcean Kubernetes cluster name stored in GitHub Secrets
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl and authenticate
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_CONNECT_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t registry.digitalocean.com/smoke/python-app:${{ github.run_number }} .
      
      - name: Login to DigitalOcean registry
        run: doctl registry login

      - name: Push Docker image
        run: |
          docker push registry.digitalocean.com/smoke/python-app:${{ github.run_number }}

  Deploy-to-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl and authenticate
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_CONNECT_TOKEN }}

      - name: Configure kubectl
        run: |
          echo "Using cluster: $DO_CLUSTER_NAME"
          doctl kubernetes cluster kubeconfig save "$DO_CLUSTER_NAME"

      - name: Update deployment
        run: |
          kubectl set image deployment/${DEPLOYMENT_NAME} \
            $CONTAINER_NAME=${REGISTRY}/${IMAGE_NAME}:${{ github.run_number }}

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/${DEPLOYMENT_NAME}
          kubectl get pods