name: "Building and Pushing Docker Image"
on:
  workflow_dispatch:   # allows manual triggering from GitHub UI
  push:
    branches:
      - main
    paths:
      - ecommerce-app/**

env:
  DO_CONNECT_TOKEN: ${{ secrets.DO_CONNECT_TOKEN }} # DigitalOcean API token stored in GitHub Secrets
  DEPLOYMENT_NAME: ${{ vars.DEPLOYMENT_NAME }}
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
  DO_CLUSTER_NAME: ${{ vars.DO_CLUSTER_NAME }} # DigitalOcean Kubernetes cluster name stored in GitHub Secrets
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl and authenticate
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_CONNECT_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t registry.digitalocean.com/dev-smoke/ecommerce-app:${{ github.run_number }} .
      
      - name: Login to DigitalOcean registry
        run: doctl registry login

      - name: Push Docker image
        run: |
          docker push registry.digitalocean.com/dev-smoke/ecommerce-app:${{ github.run_number }}

      - name: Checkout deployment branch
        run: |
          git fetch origin
          git checkout app-manifests

      - name: Update deployment.yaml with new image
        run: |
          # Update the image tag in deployment.yaml
          sed -i 's|registry.digitalocean.com/dev-smoke/ecommerce-app:.*|registry.digitalocean.com/dev-smoke/ecommerce-app:${{ github.run_number }}|g' app-manifests/Deployment/deployment.yaml
          
      - name: Commit and push updated deployment.yaml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app-manifests/Deployment/deployment.yaml
          git commit -m "Update image tag to ${{ github.run_number }}" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}